[package]
name = "adrnaln-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adrnaln = "0.1.1"
clap = {  version="4.5.4" }
tokio = "1.37.0"
